twig:
    default_path: '%kernel.project_dir%/templates'

    # activation du th√®me Bootstrap 5 pour les formulaires
    form_themes: ['bootstrap_5_layout.html.twig']

    globals:
        site_name: '%app.site_name%'

when@test:
    twig:
        strict_variables: true
